import * as firebase from 'firebase';
// Config file is generated by firebase.google.com for web app
const config = {
  apiKey: "AIzaSyC6Yi3Oj0YJx1KHIkLHazplCIIGkT8_HLg",
  authDomain: "goal-coach-05.firebaseapp.com",
  databaseURL: "https://goal-coach-05.firebaseio.com",
  projectId: "goal-coach-05",
  storageBucket: "goal-coach-05.appspot.com",
  messagingSenderId: "802957246852"
};

export const firebaseApp = firebase.initializeApp(config);
